# Generated by Django 4.2.4 on 2023-08-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrekDetails",
            new_name="TrekDetail",
        ),
    ]
