# Generated by Django 4.2.4 on 2023-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_trekdetail_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="trekdetail",
            name="image",
            field=models.ImageField(null=True, upload_to="TrekImages"),
        ),
    ]
