# Generated by Django 4.2.4 on 2023-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_trekdetail_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="TrekImages")),
                ("imageName", models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name="trekdetail",
            name="image",
        ),
    ]
