# Generated by Django 4.2.4 on 2023-08-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_trekdetail_imagefk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trekdetail",
            name="imageFK",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.photo"
            ),
        ),
    ]
