# Generated by Django 4.2.4 on 2023-08-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_trekdetail_imagefk"),
    ]

    operations = [
        migrations.AddField(
            model_name="trekdetail",
            name="category",
            field=models.CharField(
                choices=[
                    ("Trek", "Treking"),
                    ("Camp", "Camping"),
                    ("Himalaya", "Himalaya"),
                ],
                default="Trek",
                max_length=10,
            ),
        ),
    ]
